### ISSUE TITLE
Windows Environment Variables

### ISSUE THREAD

**Issue by shapi78** [graduway/psick#100]
On Linux environment, especially on Jenkins servers we create environment variables which  derived from AWS tags.  We should create similar mechanism for Windows servers, especially on Jenkins Slaves

**Comment by antgel** [comment]
@alvagante Long item, hope all well. Can you implement this?

**Comment by alvagante** [comment]
Hei @antgel , yes, going to give it a look. but will be able to work on it next week.

**Comment by alvagante** [comment]
A first look here does not seem to make distictions between Linux and Windows for the ec2 tags facts:
https://github.com/graduway/ec2tagfacts/blob/master/lib/facter/ec2_tag_facts.rb 
In the output of facter -p on Windows do you see any ec2 related fact?

**Comment by antgel** [comment]
@shapi78 Please let @alvagante know what you found.

**Comment by shapi78** [comment]
@alvagante facter -p does shows the variables but it stays as facts, in Linux we transformed it to profile environment variables, in Windows it is more complicated to transform it to environment variables

![screenshot from 2018-12-11 15-10-37](https://user-images.githubusercontent.com/6275980/49802964-2b957f80-fd57-11e8-9105-7722a13d5868.png)

**Comment by alvagante** [comment]
@shapi78 by environment variables I suppose you mean the ones we set at top scope in manifests/site.pp based on these facts. (https://github.com/graduway/psick/blob/production/manifests/site.pp#L23) If so, what's weird is that behavious should be the same for Linux and Windows: if a fact like ec2_tag_env fact is set, then in https://github.com/graduway/psick/blob/production/manifests/site.pp#L26 the $env top scope variable is set. And there should not be difference between Linux and Windows in using it.
What's exactly the expected outcome? What variables, based on ec2 facts, do you need in Windows Jenkins slaves?
