### ISSUE TITLE
Generate keypair for hiera eyaml and copy to correct place on puppet master

### ISSUE THREAD

**Issue by antgel** [graduway/psick#2]
Using userdata / terraform as discussed.

https://github.com/voxpupuli/hiera-eyaml for the docs.

**Comment by shapi78** [comment]
@antgel -  please create private bucket to store the eyaml encryption keys. The keys will be downloaded to puppet server at bootstrap to encrypt and decrypt eyaml data

**Comment by antgel** [comment]
And I should ensure access only to role "puppet"?

**Comment by shapi78** [comment]
Just make it private - I'll take it from there

**Comment by antgel** [comment]
@shapi78 Do you think we should be creating the bucket [in Terraform](https://www.terraform.io/docs/providers/aws/r/s3_bucket.html) or manually?

**Comment by shapi78** [comment]
manually

**Comment by shapi78** [comment]
Keys were not copied to new dev puppet

**Comment by shapi78** [comment]
Fixed
