### ISSUE TITLE
ec2-plugin configuration not restoring from SCM Sync

### ISSUE THREAD

**Issue by shapi78** [graduway/psick#22]
Jenkins plugin configuration (mainly ec2-plugin) did not restore while installing Jenkins with puppet

**Comment by alvagante** [comment]
In the jenkins instance I found on Sandbox I saw the plugins installed.
Plugins configuration should be synced via SCM plugin, which also should be available (eventually a manual jenkins service restart is needed after the first Puppet configuration run).
If some ec2 plugin settings are still missing now (after the scm looks to have synced configs (waiting for confirmation about that) then it could store some info outside the dir synced by scm)

**Comment by antgel** [comment]
If you mean plugin *install*, then we have to do it. If you mean plugin *configuration*, I agree, and as I said we should open a bug on the SCM Sync plugin if it doesn't do that.

Having said that, a manual Jenkins service restart should be easy enough to automate via the first Puppet configuration run, no? @alvagante

**Comment by alvagante** [comment]
@antgel actually we DO trigger a service restart via Puppet, as reported via gmail chat, but it looks not to be enough. Installation of plugin should already be done  here: https://github.com/graduway/psick/blob/production/hieradata/role/jenkins.yaml#L35 
Configuration should come via SCM sync. I still haven't understood anyway, if what you see currently on the sandbox instance (after a manual Jenkins service restart by me and, maybe, some other manual changes done yesterday by @shapi78 ) is ok or not.

**Comment by antgel** [comment]
@shapi78 Please can you and @alvagante schedule some time to work on this together, even possibly on the server simultaneously.

**Comment by alvagante** [comment]
@shapi78 I am available next week (starting Monday 19) for a video call where we run a test from scratch and see where are the problems and the timings with Jenkins setup.
As a reminder, just found this, which may be relevant to https://github.com/graduway/psick/issues/21  and could be worth considering while troubleshooting https://github.com/jenkinsci/jenkins/pull/3166

**Comment by antgel** [comment]
@shapi78 Please coordinate with @alvagante

**Comment by antgel** [comment]
@shapi78 Ping.

**Comment by antgel** [comment]
Closing as we're no longer using this plugin.
