### ISSUE TITLE
VPN routes all traffic through gateway

### ISSUE THREAD

**Issue by antgel** [graduway/psick#23]
It should just route traffic destined for the destination IP address. [This link](https://community.openvpn.net/openvpn/wiki/IgnoreRedirectGateway) may help.

Reproduce:
- Connect to VPN.
- Go to https://www.whoismyisp.org/ in a browser.

@alvagante @shapi78 Who should fix this?

**Comment by alvagante** [comment]
So, I'm a bit busy this week but I'm more free starting from Monday, so I can work on this, even if @shapi78 has done the openvpn setup so may he can better work on it.

**Comment by antgel** [comment]
@alvagante Great, it's not desperately urgent, will be happy if you'll do it.

**Comment by shapi78** [comment]
I already handled it with route injected to the client, in my laptop it works ok, we need to check it on other environment:

on hieradata/role/openvpn.yaml:

openvpn::servers:
  'graduway-vpn':
    country: 'IL'
    province: 'TLV'
    city: 'Raanana'
    organization: 'Graduway'
    email: 'development@graduway.com'
    server: '192.168.200.0 255.255.255.0'
    push: ["route 172.16.0.0 255.255.0.0"]


The push route should only route the local subnet AWS VPC subnet through the VPN

**Comment by alvagante** [comment]
@shapi78 will 172.16/16 be the default vpc subnet in all the different environments/regions?
If yes, what you mentioned for hieradata/role/openvpn.yaml is enough otherwise we should provide different data for different environments or, better, use a fact to identify the network.

**Comment by antgel** [comment]
It was a "feature" of NetworkManager. :roll_eyes:
