### ISSUE TITLE
Puppet not installing IIS

### ISSUE THREAD

**Issue by antgel** [graduway/psick#41]
On our web server, following error:
```
C:\Windows\system32>puppet agent -t
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Serve
r Error: Evaluation Error: Error while evaluating a Function Call, Could not fin
d class ::iis for win-rpbf6jnggr7.sandbox.graduway.com (file: /etc/puppetlabs/co
de/environments/production/modules/psick/manifests/iis.pp, line: 35, column: 3)
on node win-rpbf6jnggr7.sandbox.graduway.com
Warning: Not using cache on failed catalog
Error: Could not retrieve catalog; skipping run

C:\Windows\system32>
```

@shapi78 Do you know what this is, have you seen it before? If not, perhaps we should involve @alvagante . Our PSICK is pretty out of date, but I would have expected this to work...

**Comment by alvagante** [comment]
Puppetlabs's iis module has to be added to Puppetfile (and deployed).
In upstream psick iis is not installed by default.

**Comment by antgel** [comment]
Thanks @alvagante. Where are we on the Jenkins pipeline that can deploy r10k? If you want to work together on it, I've been working a lot lately on Jenkins Pipeline.

@shapi78 Please install the IIS module so it works out of the box.

**Comment by antgel** [comment]
@alvagante @shapi78 Ping

**Comment by alvagante** [comment]
@antgel haven't done further works on the Jenkinsfile 
For installation of iis just add to Puppetfile something like:
mod 'puppetlabs-iis', '4.3.1'
and run r10k
