### ISSUE TITLE
Move graduway.com domain from godaddy to Route 53

### ISSUE THREAD

**Issue by antgel** [graduway/psick#5]
In preparation for move to terraform. * Note this is only for graduway.com domain. *
- Add Route 53 zone data to terraform with relevant `aws_*` directives.
- Use [dns-compare](https://github.com/joemiller/dns_compare) after importing zone to Route 53, before we change the main nameservers.
- Change the main nameservers at an agreed time.

**Comment by shapi78** [comment]
Domain moved
