### ISSUE TITLE
EC2 tags to find their way to shell environment variables

### ISSUE THREAD

**Issue by antgel** [graduway/psick#63]
This would make life really easy e.g. in a Jenkins pipeline. Let's say the pattern is something like `$EC2_TAG_Env` for a tag named `Env`. @alvagante @shapi78 What do you think is the best way to make this happen?

**Comment by alvagante** [comment]
@antgel we have ec2_tags as facts, so it's easy to create a file like /etc/profile.d/ec2.sh where such tags are exported as shell environment variables
