### ISSUE TITLE
Jenkins user .ssh directory problem

### ISSUE THREAD

**Issue by antgel** [graduway/psick#7]
I guess this could be an upstream bug, but not sure so opening here. Seen on a fresh Jenkins master, on the second run of `puppet apply --test`.

**Error: Could not set 'present' on ensure: No such file or directory @ dir_s_mkdir - /var/lib/jenkins/.ssh/config20171201-4385-1o185ut.lock at /etc/puppetlabs/code/environments/production/modules/psick/manifests/openssh/config.pp:68
Error: Could not set 'present' on ensure: No such file or directory @ dir_s_mkdir - /var/lib/jenkins/.ssh/config20171201-4385-1o185ut.lock at /etc/puppetlabs/code/environments/production/modules/psick/manifests/openssh/config.pp:68
Wrapped exception:
No such file or directory @ dir_s_mkdir - /var/lib/jenkins/.ssh/config20171201-4385-1o185ut.lock
Error: /Stage[main]/Psick::Jenkins/Psick::Openssh::Config[jenkins]/File[/var/lib/jenkins/.ssh/config]/ensure: change from 'absent' to 'present' failed: Could not set 'present' on ensure: No such file or directory @ dir_s_mkdir - /var/lib/jenkins/.ssh/config20171201-4385-1o185ut.lock at /etc/puppetlabs/code/environments/production/modules/psick/manifests/openssh/config.pp:68**

This then causes:
**(/Stage[main]/Psick::Jenkins::Tp/Tp::Install[jenkins]/Service[jenkins]) Dependency File[/var/lib/jenkins/.ssh/config] has failures: true
(/Stage[main]/Psick::Jenkins::Tp/Tp::Install[jenkins]/Service[jenkins]) Skipping because of failed dependencies
(/Stage[main]/Psick::Jenkins::Scm_sync/Exec[trigger_jenkins_scm_sync]) Dependency File[/var/lib/jenkins/.ssh/config] has failures: true
(/Stage[main]/Psick::Jenkins::Scm_sync/Exec[trigger_jenkins_scm_sync]) Skipping because of failed dependencies
(/Stage[main]/Psick::Jenkins::Scm_sync/Exec[jenkins_reload]) Dependency File[/var/lib/jenkins/.ssh/config] has failures: true
(/Stage[main]/Psick::Jenkins::Scm_sync/Exec[jenkins_reload]) Skipping because of failed dependencies**

Running `puppet apply --test` again didn't help.

**Comment by alvagante** [comment]
This PR to puppet-psick should solve the issue: 
https://github.com/example42/puppet-psick/pull/30
(i'm testing it now).
The PR also add the option to disable the setup wizard (and securtity), in Hiera set it with:
psick::jenkins::disable_setup_wizard: true

**Comment by alvagante** [comment]
This should be fixed, closing.
