### ISSUE TITLE
Disable hostname, hosts and dns on psick::pre::linux_classes

### ISSUE THREAD

**Issue by shapi78** [graduway/psick#8]
## Expected Behavior 
On common.yaml:
psick::pre::linux_classes:

Please disable:
hostname: '::psick::hostname'
hosts: '::psick::hosts::resource'
dns: '::psick::dns::resolver'

## Actual Behavior
While new agent starts these modules affect the connections to to the puppet master
we can leave route53 to handle dns resolving and cloud-init to set hostname and handle host file

**Comment by antgel** [comment]
@shapi78 What's the status? Connecting to the puppet master seems to work fine.

**Comment by antgel** [comment]
@shapi78 Ping
